name: API Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - Deployment

env:
  AZURE_WEBAPP_NAME: SwampLocksAPI
  AZURE_WEBAPP_PACKAGE_PATH: './myapp'
  DOTNET_VERSION: "8.x"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build with dotnet
        run: |
          pushd './SwampLocksAPI'
          dotnet build --configuration Release
          popd
          
      - name: Publish with dotnet
        run: |
          mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          pushd './SwampLocksAPI'
          dotnet publish -c Release -o ../${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          popd

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    name: Deploy To Azure
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v1
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
