# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - swamplocksDbUpdater

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'AlphaVantage'  # Set the correct path to your function project (AlphaVantage folder)
  DOTNET_VERSION: '9.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read # This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: bash
        run: |
          pushd './AlphaVantage'  # Navigate to the AlphaVantage folder where your .csproj file is
          dotnet build --configuration Release --output ./output  # Builds the project
          popd

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.__clientidsecretname__ }}
          tenant-id: ${{ secrets.__tenantidsecretname__ }}
          subscription-id: ${{ secrets.__subscriptionidsecretname__ }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'swamplocksDbUpdater'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'

      - name: Restart Azure Function App
        run: |
          az functionapp restart --name swamplocksDbUpdater --resource-group <YourResourceGroupName>
        env:
          AZURE_CLIENT_ID: ${{ secrets.__clientidsecretname__ }}
          AZURE_TENANT_ID: ${{ secrets.__tenantidsecretname__ }}
          AZURE_CLIENT_SECRET: ${{ secrets.__clientsecretname__ }}
